### ISSUE TITLE
auto-release command

### ISSUE THREAD

**Issue by Kruimeldief** [jxsl13/zcatch#106]
Not sure why people would rather play release games in zCatch than join a gDM or gCTF server, but this is how it is. So can the release game be facilitated better by adding a new commando that enables/disables auto-releasing killed players. For instance _/autorelease_ or _/autorelease <time_between_kill_and_release>_?

If such a command is implemented, perhaps it can be turned off for all once there are 11 players in the server (10 + 1 buffer tee) with a notification message saying "_Auto-release turned off. Enough players to end the round_."?

This feature is meant as optional so the command should be optional for each player. So no mandatory auto-release for all players.

**Comment by jxsl13** [comment]
You do play warmup (gDM) until you hit 5 ingame players in total. After that the warmup ends and you play normal zCatch.
This is the zCatch behavoir of the version implemented for Teeworlds 0.7.x

Any such command like autorelease is against the principle of the whole gametype, which is the zCatch gameplay.
I do not want to degrade zCatch into gDM.
We had this situation where zCatch players tried to enforce the whole server to play "rls game" aka gDM, despite the fact that there were enough players to start a round of normal zCatch.
Thus I am explicitly working against the term "rls game" in order to avoid the 0.6 toxic shithole as discribed above.

Warmup mode tries to keep the players having some fun without having enough players to start a round

**Comment by jxsl13** [comment]
Any players trying to enforce "rls game" by kickvoting, specvoting players that are trying to play  normal zCatch after having hit the mark of 5 ingame players can be reported (Simply zCatch servers -> https://pic.zcat.ch)
or at their respective places mentioned on those server's message of the day/server info.

**Comment by jxsl13** [comment]
The second problem that we do get when only a small number of players can actually disable the warmup is that they become able to end the round.

"Not being able to win the round" on the other hand makes the zCatch gametype somewhat obsolete in that warmup phase, so gDM is a better alternative for practicing purposes.

If only a few players can end the round, the whole ranking system becomes somewhat obsolete and exploitable with a single person that can connect with (in my default case) up to two clients per IP, allowing them to join a server, disable auto release and kill the other player (their dummy) and earn wins, score points(these usually start at >= 5 players), whatever.


What happens in total with such a command:
people might disable auto release

start killing other players even tho they cannot win a round.

it makes no sense to watch a player that cannot win the match play

people leave the game.

bad influence on the whole community (which is small already)

**Comment by jxsl13** [comment]
in 0.6 Savander introduced a bad variant of zCatch, which I do not support. The only interesting improvement was probably the ranking system.
All of the other aspects were sadly bad gameplay-wise, especially the number of 10 players needed to end a round.
this from my point of view was a hacky way to prevent people from exploiting the ranking system by increasing the player count.
As zCatch became less popular, this high limit made it nearly impossible to get a game of zCatch going that could actually be finished.
